apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: index-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html  # Ensures the file is mounted as index.html
      volumes:
        - name: index-volume
          configMap:
            name: app1-index  # The ConfigMap to mount
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
