Vagrant.configure("2") do |config|

    config.vm.synced_folder "./shared/", "/shared_folder"

    config.vm.box = "debian/bullseye64"
    config.vm.box_version = "11.20241217.1"

    config.vm.define "nthimoniS" do |s|
        s.vm.hostname = "nthimoniS"

        # Define the number of CPUs and amount of RAM for the VM
        s.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1 
            vb.customize ["modifyvm", :id, "--name", "nthimoniS"]
        end

        s.vm.network "private_network", ip: "192.168.56.110"
        s.vm.provision "shell", path: "./scripts/server.sh"

    end

    config.vm.define "nthimoniSW" do |sw|
        sw.vm.hostname = "nthimoniSW"

        # Define the number of CPUs and amount of RAM for the VM
        sw.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--name", "nthimoniSW"]
        end

        sw.vm.network "private_network", ip: "192.168.56.111"
        sw.vm.provision "shell", path: "./scripts/worker.sh"

    end

end
